export const past_speakers_data = [
  {
    name: "Dharamveer Singh Chauhan",
    des: "Co-Founder and CEO, Zo World and Zostel",
    imgURL: "/pastspeaker/Dharamveer Singh Chouhan.jpg",
    xURL: "https://twitter.com/dvcoolster",
    instaURL: "https://www.instagram.com/dvcoolster/?hl=en",
    linkedinURL: "https://www.linkedin.com/in/dvcoolster/?originalSubdomain=in",
  },
  {
    name: "Kaustav Mukherjee",
    des: "Managing Director, BCG",
    imgURL: "/pastspeaker/Kaustav Mukherjee.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/smartbong/?originalSubdomain=in",
  },
  {
    name: "Ganesh Rengaswami",
    des: "Co-Founder &Managing Partner, Quona Capiral",
    imgURL: "/pastspeaker/Ganesh Rengaswamy.jpg",
    xURL: "https://twitter.com/grengaswamy",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/ganeshrengaswamy/?originalSubdomain=sg",
  },
  {
    name: "Sandeep Jain",
    des: "Founder, CEO, GFG",
    imgURL: "/pastspeaker/Sandeep Jain.jpg",
    xURL: "https://twitter.com/sandeep_jain",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/sandeep-jain-/?originalSubdomain=in",
  },
  {
    name: "Amit Somani",
    des: "Managing partner, Prime ventures",
    imgURL: "/pastspeaker/Amit Somani.jpg",
    xURL: "https://twitter.com/amitsomani",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/thesomani/?originalSubdomain=in",
  },
  {
    name: "Anubhav Dubey",
    des: "CO-Founder, Chai Sutta Bar",
    imgURL: "/pastspeaker/Anubhav Dube.jpg",
    xURL: "https://twitter.com/tbhanubhav?lang=en",
    instaURL: "https://www.instagram.com/anubhavdubey1/?hl=en",
    linkedinURL:
      "https://www.linkedin.com/in/anubhavdubey/?originalSubdomain=in",
  },
  {
    name: "Krishna Vedati",
    des: "Co-Founder and CEO, Tynker",
    imgURL: "/pastspeaker/Krishna Vedati.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/krishnavedati/",
  },
  {
    name: "BV Jagaddesh",
    des: "Managing Director, Kaaj Ventures",
    imgURL: "/pastspeaker/BV Jagadeesh.jpg",
    xURL: "https://twitter.com/bvjagadeesh?lang=en",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/bvjagadeesh/",
  },
  {
    name: "Aditi Pal",
    des: "CFO, Bewkoof.com",
    imgURL: "/pastspeaker/Aditi Pal.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/aditi-pai-67383281/?originalSubdomain=in",
  },
  {
    name: "Priya Sharma",
    des: "Co-Founder, ZestMoney",
    imgURL: "/pastspeaker/Priya Sharma.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/priya-sharma-635a223/?originalSubdomain=in",
  },
  {
    name: "Sachin Tomar",
    des: "Co-founder and CTO, Biconomy",
    imgURL: "/pastspeaker/Sachin Tomar.jpg",
    xURL: "https://twitter.com/schin_tomar?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/sachintomar2271/?originalSubdomain=ae",
  },
  {
    name: "Gunjan Shukla",
    des: "ex-CFO, Paypal",
    imgURL: "/pastspeaker/Gunjan Shukla.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/gunjanshukla/?originalSubdomain=in",
  },
  {
    name: "Garv Malik",
    des: "CMO, Slice",
    imgURL: "/pastspeaker/Garv Malik.jpg",
    xURL: "https://twitter.com/malikgarv?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor",
    instaURL: "https://www.instagram.com/imgarvmalik/?hl=en",
    linkedinURL:
      "https://www.linkedin.com/in/gunjanshukla/?originalSubdomain=in",
  },
  {
    name: "Gaurav Agarwal",
    des: "Co-Founder, 1MG",
    imgURL: "/pastspeaker/Gaurav Agarwal.jpg",
    xURL: "https://twitter.com/agarwal_gaurav?lang=en",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/agarwalga/?originalSubdomain=in",
  },
  {
    name: "Deepak Tuli",
    des: "co-founder and ex-coo, goibibo and Eka Care",
    imgURL: "/pastspeaker/Deepak Tuli.jpg",
    xURL: "https://twitter.com/deepaktuli",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/deepak-tuli-62a8617/?originalSubdomain=in",
  },
  {
    name: "Amit Kumar Agarwal",
    des: "Founder and CEO, Nobroker",
    imgURL: "/pastspeaker/Amit Kumar Agarwal.jpg",
    xURL: "https://twitter.com/amitkumara?lang=en",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/amit-kumar-agarwal-5b30301/?originalSubdomain=in",
  },
  {
    name: "Piyush Agarwal",
    des: "Founder, Director at crickbuzz",
    imgURL: "/pastspeaker/Piyush Agarwal.jpg",
    xURL: "https://twitter.com/piyush_agrawal",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/piyushagrawal2/?originalSubdomain=in",
  },
  {
    name: "Dr Radhakrishnan Pillai ",
    des: "Cheif Leadership Coach, Chanakya Aanvikshiki",
    imgURL: "/pastspeaker/Dr. Radhakrishnan Pillai.jpg",
    xURL: "https://twitter.com/rchanakyapillai",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/rchanakyapillai/?originalSubdomain=in",
  },
  {
    name: "Dr Sangita Reddy",
    des: "MD, Apollo Hospitals",
    imgURL: "/pastspeaker/Dr. Sangita Reddy.jpg",
    xURL: "https://twitter.com/drsangitareddy",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/drsangitareddy/?originalSubdomain=in",
  },
  {
    name: "Vishal Jindal",
    des: "Founder and Co CEO, Biryani By Kilo",
    imgURL: "/pastspeaker/Vishal Jindal.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/vishal-jindal-7424282/?originalSubdomain=in",
  },

  {
    name: "Praharsh Sharma",
    des: "MD, Goldman Sachs",
    imgURL: "/pastspeaker/Praharsh Sharma.jpg",
    xURL: "https://twitter.com/praharsh_sharma",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/praharsh/?originalSubdomain=in",
  },

  {
    name: "Sanjeev Mehta",
    des: "MD, Standard chartered Bank India",
    imgURL: "/pastspeaker/Sanjeev Mehta.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/sanjeevmehtascbank/?originalSubdomain=in",
  },
  {
    name: "Amitava Saha",
    des: "Co-Founder and CEO, XpressBees and FirstCry",
    imgURL: "/pastspeaker/AmitavaSaha.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/amitavasaha73/?originalSubdomain=in",
  },

  {
    name: "Vishwanathan Iyer",
    des: "VP Sales & Architecture, CISCO",
    imgURL: "/pastspeaker/Vishwanathan Iyer.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/vishviyer/?originalSubdomain=sg",
  },

  {
    name: "Ankit Aggarwal",
    des: "Founder & CEO, Unstop",
    imgURL: "/pastspeaker/Ankit Aggarwal.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/unstoppableankit/",
  },

  {
    name: "Murli Thirumale",
    des: "Co-Founder & VP, Portworx",
    imgURL: "/pastspeaker/Murli Thirumale.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/murlithirumale/",
  },
];

export const present_speakers_data = [
  {
    name: "Siddharth Maheshwari",
    des: "Co-Founder at Newton School",
    imgURL: "/presentspeaker/siddharth netwon school.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/maheshwarisiddharth/",
  },
  {
    name: "Vijender Singh Chouhan",
    des: "Drishti IAS Interviewer",
    imgURL: "/presentspeaker/vijendar.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/vijendermasijeevi/",
  },
  {
    name: "Rajeev Samant",
    des: "CEO and Founder at Sula Vineyards",
    imgURL: "/presentspeaker/rajeev samant sula vineyards.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/rajeev-samant-a85396/?originalSubdomain=in",
  },
  {
    name: "Nitin Sharma",
    des: "Founder & CEO at GoWaterless",
    imgURL: "/presentspeaker/nitin sharma go waterless.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/nitin-sharma-%E2%9C%85-64a866194/?originalSubdomain=in",
  },
  {
    name: "Sanjeev Bikhchandani",
    des: "Co-Founder at InfoEdge (Naukri.com, Jeevansathi.com, 99acres.com, shiksha.com, naukrigulf.com)",
    imgURL: "/presentspeaker/sanjeev infoedge.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/sanjeev-bikhchandani-501261/?originalSubdomain=in",
  }, {
    name: "Jay Prakash",
    des: "Founder at Silence Laboratories ",
    imgURL: "/presentspeaker/jay prakash silence laboratories.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/jayprakashiitbhu/?originalSubdomain=sg",
  },
  {
    name: "Prashant ",
    des: "Co-Founder at Spheron Networks",
    imgURL: "/presentspeaker/prashant maurya sphreon.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/techprashantmaurya/?originalSubdomain=ae",
  },
  {
    name: "Samir Kumar Mishra",
    des: "Director & Head of Security Business, India & SAARC at Cisco",
    imgURL: "/presentspeaker/sameer kumar mishra.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/samir-kumar-mishra-494858a/?originalSubdomain=in",
  },
  {
    name: "Kaushik Mohanty",
    des: "Director of Engineering t Cisco",
    imgURL: "/presentspeaker/kaushik mohanty.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/kaushik-mohanty-3b908252/?originalSubdomain=in",
  },
  {
    name: "Saurabh Singh",
    des: "Director at Trifecta Capital",
    imgURL: "/presentspeaker/saurabh singh .jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/saurabh-singh-bb6b4022/?originalSubdomain=in",
  },
  {
    name: "Ashutosh Sharma",
    des: "Investments and M&A Head at Prosus",
    imgURL: "/presentspeaker/ashutosh sharma.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/ashutosh-sharma-ba90312/?originalSubdomain=in",
  },
  {
    name: "Abhishek ",
    des: "VP Investments at IAN",
    imgURL: "/presentspeaker/abhishek kakkar .jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/kakkarabhishek/?originalSubdomain=in",
  },
  {
    name: "Shashank Randev",
    des: "Co-Founder at 100X.VC",
    imgURL: "/presentspeaker/shashan ranadev.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/shashankrandev/?originalSubdomain=in",
  },
  {
    name: "Sam Kamath",
    des: "MD at Axis Capital",
    imgURL: "/presentspeaker/sam kamath.png",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/sam-kamath-8480a62/?originalSubdomain=in",
  },
  {
    name: "Somesh Jaiswal",
    des: "Founder & CEO at MakerSharks",
    imgURL: "/presentspeaker/somesh jaiswal.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/someshjaiswal15/",
  },
  {
    name: "Vivek Prakash",
    des: "Product Manager - Growth at Instabase",
    imgURL: "/presentspeaker/vivek prakash.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/vivekpb/?originalSubdomain=in",
  },
  {
    name: "Udit G",
    des: "COO at Google Cloud India",
    imgURL: "/presentspeaker/uditg.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/uditgoyal/?originalSubdomain=in",
  },
  {
    name: "Dhanush Ram",
    des: "Investment Manager at Speciale Invest",
    imgURL: "/presentspeaker/dhanush ram.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/dhanush-ram/",
  },
  {
    name: "Mohit Sewak",
    des: "Principal AI Researcher at Microsoft",
    imgURL: "/presentspeaker/mohit sewak.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/mohitsewak/?originalSubdomain=in",
  },
  
];