'use client';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { fontSans } from "@/lib/fonts";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";
import React from "react";
import { ParallaxProvider } from 'react-scroll-parallax';
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "E-Summit'24",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="flex min-h-screen flex-col">
            <Navbar/>
            <ParallaxProvider>
          <main className="flex-1 herobackground">
              {children}
          </main>
                </ParallaxProvider>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
