'use client';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { fontSans } from "@/lib/fonts";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";
import "./globals.css";
import React from "react";
import { ParallaxProvider } from 'react-scroll-parallax';
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "E-Summit'24",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-black font-sans antialiased",
          fontSans.variable
        )}
      >
        <header className="w-[100%] sticky z-10 top-8 max-w-[76.5rem] m-auto lg:p-0 ">
          <div className="w-full rounded-full z-10 bg-background  opacity-95  md:absolute fixed mt-1">
            <Navbar />
          </div>
        </header>
        <div className="relative flex min-h-screen flex-col">
          <main className="flex-1">
          <ParallaxProvider>
          <main className="flex-1 herobackground">
              {children}
          </main>
                </ParallaxProvider>
          </main>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
